name: Lint Order Service

on:
  push:
    branches: [main]
    paths:
      - 'order/**'
  pull_request:
    branches: [main]
    paths:
      - 'order/**'

jobs:
  lint:
    name: Run golangci-lint on Order Service
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54.2
          args: --timeout 5m --verbose
          working-directory: ./order
